# Generated by Django 3.1.1 on 2020-09-28 15:59

from django.db import migrations, models
import spacescoops.models


class Migration(migrations.Migration):

    dependencies = [
        ('spacescoops', '0008_auto_20170124_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'translations__language_code': 'en'}, related_name='articles', to='spacescoops.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=spacescoops.models.get_file_path_article_attachment),
        ),
        migrations.AlterField(
            model_name='originalnewssource',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='partners'),
        ),
    ]
