# Generated by Django 3.1.2 on 2020-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacescoops', '0009_auto_20200928_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='scoops/'),
        ),
    ]
