# Generated by Django 3.1.1 on 2020-09-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_auto_20160213_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='institutions'),
        ),
    ]
