# Generated by Django 3.2.25 on 2025-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20200928_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='active',
            field=models.BooleanField(default=True, help_text='If unchecked, the institution will not be shown in the list of institutions'),
        ),
    ]
